### ISSUE TITLE
How to access child properties?

### ISSUE THREAD

**Issue by GenieTim** [freearhey/wikidata#11]
Thank you very much for providing this package! I have the following problem: I would like to access e.g. property [P1033](https://www.wikidata.org/wiki/Property:P1033), which is a child of [P4952](https://www.wikidata.org/wiki/Property:P4952). How can I access this using this library? For example, entity [Q49546](https://www.wikidata.org/wiki/Q49546): when accessing P4952 on Q59546, I only get 
```
"P4952" => Wikidata\Property^ {#576
        +id: "P4952"
        +label: "safety classification and labelling"
        +value: "Regulation (EC) No. 1272/2008, NFPA 704: Standard System for the Identification of the Hazards of Materials for Emergency Response"
      }
```
without any children (no GHS properties). Trying to access the child properties (P1033) directly on the root entity (Q59546) does not help, as they are not set there. How can I achive this? If this is not yet possible, do you accept PRs?

**Comment by freearhey** [comment]
Hello. Sorry for taking so long to answer, too much to do. As for your question, this version of the library does not really provide access to the sub-properties. Values of all properties come in the form of strings and in the current version it is not possible to get their ID. 

I will try in the coming days to find some solution, but I can't promise anything. And if you are still interested in making a PR I will certainly accept it.

**Comment by GenieTim** [comment]
No worries, thanks for the answer. I will have time to look into it in ca. 2 weeks and could/will then submit a PR.

**Comment by freearhey** [comment]
@GenieTim I wanted to say thanks for the help! You did a great job, especially with the SPARQL query! 

As a result, I had to change the structure a little bit, but I hope now there will be no problems with getting any data. 

As for the answer to your initial question, in the new version this can be done like this:

```php
$entity = $wikidata->get('Q49546');

$entity->properties->get('P4952')->values->first(function ($value) {
    return $value->id === 'Q2005334';
})->qualifiers->first(function ($qualifier) {
    return $qualifier->id === 'P1033';
});
```

And result should be like this:

```php
Qualifier {
  id: "P1033"
  label: "GHS signal word"
  value: "danger"
}
```
