### ISSUE TITLE
wikipedia_article is completely bogus

### ISSUE THREAD

**Issue by RemyNovactive** [freearhey/wikidata#18]
In the search function, a piece of code create an url 'wikipedia_article'.

```
$collection = $wikidata->search($keyword);
```

This url is the simple concatenation of the domain name and the label. 
```
        $output = $collection->map(function ($item) use ($lang) {
            $item['wikipediaArticle'] = 'https://' . $lang . '.wikipedia.org/wiki/' . rawurlencode($item['label']);
            return new SearchResult($item, $lang);
        });
```
But the label does not contain the differentiation information between the different results. So, sometimes they all have the same URL... 

![image](https://user-images.githubusercontent.com/61149932/90529893-814d3c80-e174-11ea-886b-56c328f93b8e.png)

**Comment by freearhey** [comment]
Thank you for noticing that! I'll see what I can do about it as soon as I have some free time.

**Comment by RemyNovactive** [comment]
I, for one, did this to get around the problem... 
```
    public function autocomplete($keyword, $limit = 10) : Collection
    {
        $wikidata = new Wikidata();
        $collection = $wikidata->search($keyword, 'fr', $limit);
        return $collection->map(static function (SearchResult $item) {
            $item->wikipedia_article = 'http://www.wikidata.org/entity/' . $item->id;
            return $item;
        });
   }
```

composer.json : 
`"freearhey/wikidata": "^3.5",` (3.5.1)

Other than that, this bundle is great. Thanks :)

**Comment by freearhey** [comment]
I have just published an [updated version](https://github.com/freearhey/wikidata/releases/tag/v3.6.0) of the package, hopefully this will finally solve this problem.
